### ISSUE TITLE
[Account] Merge 후 버튼 및 버튼 리스트 수정

### ISSUE THREAD

**Issue by kimInDa** [FRONTENDSCHOOL6/react-project-11#38]
Account 페이지 레이아웃과 Button 및 Button List 를 병합한 후 수정사항 요청 드려요.
1. 버튼 전체 리스트 상하 여백 넣기
![Image](https://github.com/FRONTENDSCHOOL6/react-project-11/assets/105577805/c6fe7949-b7a3-48db-96e3-21162b32b93d)

2. 버튼 사이 간격 주기
3. 버튼 내 글자 굵기(font-weight) 400으로 변경
4. 버튼 border-radius 주기
7. 버튼 콘솔 에러 
![Image](https://github.com/FRONTENDSCHOOL6/react-project-11/assets/105577805/64185679-6648-466f-a44d-2b60e3d5eab5)

**Comment by summer787** [comment]
✅버튼 사이 간격 주기
✅버튼 내 글자 굵기(font-weight) 400으로 변경
✅버튼 border-radius 주기
✅버튼 콘솔 에러  
수정했습니다
